### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it.

### ISSUE THREAD

**Issue by nmtuan200793** [othiym23/node-continuation-local-storage#110]
I'm using this package with Bluebird promise. It works fine, but I get the following warning: 
(Node: 13324) Warning: a promise was created in a handler, but was not returned from it, see http://goo.gl/rRqMUw.
Could have a way to resolve or ignore it?

Thanks,

**Comment by loyaltymethods** [comment]
Ignore is simple - just set BLUEBIRD_WARNINGS=0 env variable. There are other ways described here:

http://bluebirdjs.com/docs/api/promise.config.html

This is particularly annoying if you are using something like Mongoose, and you choose to use Bluebird for the promise library, but you are using callbacks for some of your Mongoose operations that also return a promise.

**Comment by nmtuan200793** [comment]
Yep, it works for me.
Thank you.
