### ISSUE TITLE
context lose with async & await

### ISSUE THREAD

**Issue by wuhw** [othiym23/node-continuation-local-storage#133]
``` js
const { createNamespace, getNamespace } = require('continuation-local-storage');

const ns = createNamespace('test');

ns.run(async () => {
    ns.set('value', 1);
    console.log(ns.get('value'));
    await asyncfun();
    console.log(ns.get('value'));
});

function asyncfun() {
    return Promise.resolve();
}

//got
1
undefined
```

**Comment by Qard** [comment]
CLS does not support async/await. You can try [cls-hooked](https://www.npmjs.com/package/cls-hooked). Side note though: [async/await support in async_hooks is currently broken in Node.js 10](https://github.com/nodejs/node/issues/20516).

**Comment by tybro0103** [comment]
I'm not sure why, but this exact code seems to be working totally fine for me with `node@10.15`, `continuation-local-storage@3.2.1`, `@babel/preset-env@7.5.4`, and `@babel/core@7.5.4`. Anyone know if something changed?
