### ISSUE TITLE
documentation ambiguous, and unclear if this library works

### ISSUE THREAD

**Issue by rick-kilgore** [othiym23/node-continuation-local-storage#15]
This may be just a documentation issue, but does this library currently work?  I must be missing something, but I can't figure out how to call it from reading README.md.  There are inconsistencies in the examples that beg the following questions:
    1. do I need to call ns.run() or ns.createContext() - are they the same?
    2. do I need to call ns.enter() and ns.exit()?  I've not been able to ever retrieve data from my namespace unless I do call ns.enter().
    3. should I add data to the namespace with ns.set('field', value) or context.field = value?  The former seems to not work.
    4. when I need to pull data out of the namespace, should I call cls.getNamespace() each time, or should I do it once at the top of each .js source file?

The best I have figured out how to do so far is if I answer my questions as follows:
    1. doesn't matter - use ns.run() or ns.createContext()
    2. yes, you HAVE to call ns.enter() (and ns.exit()?)
    3. ns.set('field', value) does not work - use context.field = value
    4. doesn't matter - call cls.getNamespace() once or each time

I've tried using the library this way with node versions 0.10.22 and 0.10.24 vm and I can't get things working right.  Here is the code I have in my express.js app (my app is coffee-script in case that makes a difference, though it shouldn't):

at app startup:

```
    cls = require('continutation-local-storage')    // at the top of the source file

    ns = cls.createNamespace('catalogRequest')
```

when a request comes in:

```
    ns.run (ctx) =>           // => is coffee-script for function() 
        ns.enter(ctx)
        ctx.traceId = traceId
        <asynchronous call chain> =>
            ns.exit(ctx)
```

in a function called later in the continuation chain:

```
    cls = require('continutation-local-storage')    // at the top of the file

    ns = cls.getNamespace('catalogRequest')
    logger.info("traceId = #{ns.get('traceId')}")
```

This call to logger.info() does manage to print out the traceId that I set when I received the request - apparent success.  But I still have two problems:
    1. if I submit two requests to my service, one after the other, the traceId logged for the second request doesn't change.  The namespace retrieves the first value I set on it (for the first request) forever.
    2. in another source file - one in a different package that is included as a library - any call to cls.getNamespace('catalogRequest') always returns null.  I can't get access to the namespace at all.

**Comment by iliakan** [comment]
@rick-kilgore  did you solve the issue w/ mongodb? Do you use this module now?
