### ISSUE TITLE
Does this suffer the same shared EE issue as domains?

### ISSUE THREAD

**Issue by CrabDude** [othiym23/node-continuation-local-storage#21]
For context see https://github.com/CrabDude/trycatch/issues/32.

One problem with AL, is that it's implemented at the wrong end of the stack to properly solve issues like this (CLS), because shared / long-lived EEs (e.g., sockets in request's forever-agent) can cause the *wrong* domain / context to be set in the EE's handlers.

The way to solve this is to attach the context at time of listen to a handler, not to EE.
```javascript
// context A
var ee = new EventEmitter()

// ... later
// context B
ee.on('connect', function() {
  // context B (not A, like domain default)
})
```

**Comment by othiym23** [comment]
Since I don't think there's anything actionable in here, and since Adam never followed up, I'm going to go ahead and close this. I'm still interested in hearing about holes or infelicities in how CLS deals with EEs, so open new issues if you have further questions or find bugs.
