### ISSUE TITLE
With generators/promises?

### ISSUE THREAD

**Issue by iliakan** [othiym23/node-continuation-local-storage#31]
I'm trying to use the module with Koa.JS.

For example, I want to pass a request id to nested execution:
```js
var createNamespace = require('continuation-local-storage').createNamespace;

module.exports = function* requestHandler(next) {
  this.reqId = Math.random();

  var request = createNamespace('request');
  request.run(function*() {
    request.set('reqId', this.reqId);
    yield next;
  });
};
```

The code above is like an example from CLS docs, but it doesn't work. Probably, because `request.run` doesn't expect a generator function and actually doesn't run it. 

How do I use CLS here?

**Comment by Qard** [comment]
I'm getting started on our koa instrumentation, so I'm digging into this a bit today.

So far, I've just tried naively porting cls-q to apply to native promises, but it just blows up the call stack. We'll see how far this rabbit hole goes...

**Comment by iliakan** [comment]
I tried to make use of it, it worked at first, reading/writing Koa context here: 
https://gist.github.com/2db4267c17274bfdad07

But in case of error, the exception is swallowed, even if I throw it from promise/catch block. Not sure why yet, the example is here:
https://gist.github.com/0b1bfbdd90e2d163287b

**Comment by Qard** [comment]
Seems my previous failure was due to my own stupidity. I figured out a fix and have submitted a PR for async-listener here: https://github.com/othiym23/async-listener/pull/25

For now, I'm using something like this to patch in promise support externally:

```
var cls = require('continuation-local-storage')
var shimmer = require('shimmer')
var slice = require('sliced')

var ns = cls.getNamespace('my-namespace')

function bind (fn) {
  return ns.bind(fn)
}

shimmer.wrap(Promise.prototype, 'then', function (then) {
  return function () {
    return then.apply(this, slice(arguments).map(bind))
  }
})
```

**Comment by mlegenhausen** [comment]
I use a more generator like approach with try and catch and no callbacks but with internal APIs:

```js
var namespace = cls.getNamespace('my-namespace');
var context = namespace.createContext();
var user = this.req.user;

namespace.enter(context);
try {
	namespace.set('user', user);
	yield next;
} finally {
	namespace.exit(context);
}
```

**Comment by iliakan** [comment]
Closing as resolved long ago.
