### ISSUE TITLE
MongoDB doesn't work out of the box - yet?

### ISSUE THREAD

**Issue by iliakan** [othiym23/node-continuation-local-storage#39]
Returned to check this module after some time.

Is it supposed to work with mongoose/mongodb out-of-the-box now? Guess, not?

MongoDb driver has a fix for domains inside. Maybe CLS could integrate w/ domains to use this fix too?

**Comment by iliakan** [comment]
P.S. Looks like solved for mongoose with monkeypatching.

**Comment by LiorRabin** [comment]
hi @iliakan, how did you manage to make it work with mongoose? I'm using v4.4.3
