### ISSUE TITLE
Works with http request?

### ISSUE THREAD

**Issue by iliakan** [othiym23/node-continuation-local-storage#44]
HTTP requests from node seem to loose the context.

Is there no async wrapper around http to keep context?

I tried this, didn't work either:
```js 
    ...
    var ns = process.namespaces.app;
    result= yield function(callback) {
      request({
        url: `${config.elastic.host}/${db}/${type}/_search`,
        method: 'POST',
        json: true,
        body: queryBody
      }, function(error, response, body) {
        ns.bind(callback)(error, body);
      });
    };
```

Do I miss anything?

**Comment by jkrems** [comment]
Are you using a newer version of io.js? More minimal repo: https://gist.github.com/jkrems/16deb968b7a66c34a3f2#file-cls-failure-js-L26-L47

The above passes on node 0.10, io.js 1.1.0 but not on io.js 1.8.4 or 2.4.0. It seems to be the response events only.

**Comment by jkrems** [comment]
Manually calling `ns.bindEmitter(res)` seems to fix it but I'm not sure why that wasn't necessary in older versions of node.

**Comment by jkrems** [comment]
Narrowed it down to https://github.com/nodejs/io.js/compare/v1.7.1...v1.8.1.

**Comment by jkrems** [comment]
Looks like it is broken since this commit: https://github.com/nodejs/io.js/commit/10e31ba56c676bdcad39ccad22ea9117733b8eb5

**Comment by jkrems** [comment]
Fix should be to use `activatorFirst` for `process.nextTick`.

~~~js
var processors = [];
if (process._nextDomainTick) processors.push('_nextDomainTick');
if (process._tickDomainCallback) processors.push('_tickDomainCallback');

massWrap(
  process,
  processors,
  activator
);
wrap(process, 'nextTick', activatorFirst);
~~~

**Comment by jkrems** [comment]
Fix: https://github.com/othiym23/async-listener/pull/42

**Comment by iliakan** [comment]
@jkrems: so this is actually a bug?

**Comment by jkrems** [comment]
@iliakan: As far as I can tell: yes. But I'm just an "innocent bystander" who ran into the same issue. I don't know how officially iojs is supported by these libraries. For iojs <=1.7.1 and all versions of node the current code works according to my tests.

**Comment by murphydanger** [comment]
Given that iojs and node.js will be merging again, shouldn't this issue be taking care of?

**Comment by jkrems** [comment]
This should be fixed now when using `async-listener@0.5.6` (should be installed automatically when re-installing dependencies/updating the shrinkwrap).

@iliakan Can you confirm?

**Comment by iliakan** [comment]
@jkrems reinstall this package from skratch and test?

**Comment by jkrems** [comment]
@iliakan Yep, that *should* do the trick.

**Comment by mpseidel** [comment]
@jkrems are you sure it should work with <code>async-listener@0.5.6</code>? Seems to be broken here but not entirely sure..

**Comment by jkrems** [comment]
@mpseidel You might be running into a separate issue. One issue with http requests in `node@>=1.8.4` was fixed in `async-listener@0.5.6`. Can you post an example where it doesn't (including what version of node you used)? I'd be happy to have a look! :)

**Comment by mpseidel** [comment]
@jkrems would be great if you could have a look at this https://gist.github.com/mpseidel/9675186639ffe44cca42 

(your repo https://gist.github.com/jkrems/16deb968b7a66c34a3f2#file-cls-failure-js-L26-L47 works in the same environment)

**Comment by jkrems** [comment]
Starts breaking between iojs-v1.6.2 and iojs-v1.6.3:

```
$ nvm run iojs-v1.6.2 request-cls-failure.js; nvm run iojs-v1.6.3 request-cls-failure.js
Running io.js v1.6.2
ok
Running io.js v1.6.3

assert.js:88
  throw new assert.AssertionError({
        ^
AssertionError: Has the right context in callback
```

**Comment by jkrems** [comment]
The offending commit: https://github.com/nodejs/node/commit/2903410aa8393a73dfbc75c5a9ba31c21ccb70dc

Initial guess is that `async-listener` only instruments the timer module but not the globals themselves.

**Comment by jkrems** [comment]
@mpseidel Nope, much easier. Sorry, should have checked your example properly first. There's a guiding rule when working with CLS and `async-listener` (not sure if it's official but it's a rule I go): Never ever require anything before cls/async-listener.

In this example: The moment `request` gets required, it will check what kind of defer function it should use - e.g. `setImmediate` vs. `process.nextTick` vs. `setTimeout(f, 0)`. It will then assign that function to a local/module identifier. Which means when CLS tries to instrument timers a moment later, that reference will still point to the old, uninstrumented version.

The fix is to always require cls first. After moving that require line to the top, your gist passes on node 4.

**Comment by mpseidel** [comment]
@jkrems you are the bes! Totally solved it for me! 

Have a great weekend.

**Comment by othiym23** [comment]
It looks like this got rounded up while I was off doing other things (mostly by the upgrade to `async-listener@0.5.6` – thanks to @Qard et al for taking care of that), so I'm going to close this issue. Thanks to all for pitching in and / or their patience!

**Comment by iliakan** [comment]
Thank you!
