### ISSUE TITLE
Release version that uses async-listener v0.5.3

### ISSUE THREAD

**Issue by dlopuch** [othiym23/node-continuation-local-storage#45]
Async-listener just merged this PR: https://github.com/othiym23/async-listener/pull/39 that fixed issues [using ES6/harmony promises with the newrelic client](https://discuss.newrelic.com/t/newrelic-1-18-breaks-es6-promises-when-used-with-async-listener-or-continuation-local-storage/24799).

Since async-listener is often brought in via cls, it would be helpful if cls would up its async-listener dependency to include 0.5.3 by default instead of relying on semver fuzzy matching

**Comment by othiym23** [comment]
Done! `continuation-local-storage@3.1.5` is released, which depends on `async-listener@0.5.6`. Thanks for filing this, and thanks for your patience in waiting me to get around to dealing with it!
