### ISSUE TITLE
Context lost with SetTimeout

### ISSUE THREAD

**Issue by cphoover** [othiym23/node-continuation-local-storage#53]
For some reason the CLS context get's lost on the setTimeout call. I'm resolve a promise on a setTimeout. If I resolve the immediately promise (w/out the setTimeout I still have the context) the values are defined, if I include the timeout the values are undefined.

Here is my example application I'm trying.

```js
//index.js
'use strict';

var Bluebird = require('bluebird');

var testAsync = require('./test_async');
// namespace has to be created first before it can be used;
var tracer = require('./tracer');

setInterval(function () {

	tracer.run(function () {
		return testAsync()
			.then(function () {
				return new Bluebird(function (resolve) {
					setTimeout(resolve, Math.random() * 500);
				});
			})
			.then(function () {
				console.log(new Date().getTime() + ' - tid test end', tracer.context.get('tid'));
				console.log(new Date().getTime() + ' - test value test end', tracer.context.get('testVal'));
				console.log('---------------------------------------------------------');
			});
	});
}, 2000);
```

```js
// tracer.js
'use strict';

var cls = require('continuation-local-storage'),
	uuid = require('node-uuid');

module.exports = {
	get context() {
		return cls.getNamespace('transaction') || cls.createNamespace('transaction');
	},
	run : function (_fn) {
		this.context.run(function () {
			this.context.set('tid', uuid.v4());
			return _fn(arguments);
		}.bind(this));
	}
};
```

```js
// test_async.js
'use strict';

var Bluebird = require('bluebird');

var tracer = require('./tracer');

module.exports = function () {

	return Bluebird
		.delay(1000)
		.then(function () {
			tracer.context.set('testVal', 1234);
			return 3;
		});
};

```

Here is the output I get

```
---------------------------------------------------------
1449865533912 - tid test end undefined
1449865533912 - test value test end undefined
---------------------------------------------------------
1449865536373 - tid test end undefined
1449865536373 - test value test end undefined
---------------------------------------------------------
1449865538012 - tid test end undefined
1449865538012 - test value test end undefined
---------------------------------------------------------
1449865540362 - tid test end undefined
...
```

In index.js when I change `setTimeout(resolve, Math.random() * 500);` to just `resolve();`
I get

```
---------------------------------------------------------
1449865577071 - tid test end be1d48f2-6156-4912-8556-a5386d737f50
1449865577071 - test value test end 1234
---------------------------------------------------------
1449865579074 - tid test end 8df4c49a-d73a-4f19-ae53-c361cfadb39f
1449865579074 - test value test end 1234
---------------------------------------------------------
1449865581074 - tid test end 3f6916c3-c898-44f4-8149-a299e443dbee
1449865581074 - test value test end 1234
---------------------------------------------------------
1449865583080 - tid test end e0dd4973-468b-484f-aaf4-1e8364ecf9f5
1449865583080 - test value test end 1234
---------------------------------------------------------
...
```

**Comment by cphoover** [comment]
I'm new to using the CLS library so if my understanding of how it is supposed to work is wrong, please let me know. Thanks!

**Comment by cphoover** [comment]
Also using node v5.2.0 for reference

**Comment by dazld** [comment]
For bluebird, you need to patch things up a little - https://github.com/TimBeyer/cls-bluebird

**Comment by cphoover** [comment]
Thanks @dazld I'll look into that.

I do have a question though. When I add a namespace.bind to the last thenable

e.g
```
   .then(tracer.context.bind(function () {
                console.log(new Date().getTime() + ' - tid test end', tracer.context.get('tid'));
                console.log(new Date().getTime() + ' - test value test end', tracer.context.get('testVal'));
                console.log('---------------------------------------------------------');
            }));
```

it seems to work... But i don't need to do it to the first one. I'm confused as to what is occurring to lose the context.  When I need to be conscious of this, so I can avoid it.

**Comment by cphoover** [comment]
??? still confused

**Comment by cphoover** [comment]
I guess I'm confused why things like cls-q or cls-bluebird need to exist.

**Comment by dazld** [comment]
sorry! been quite busy here, but you can see a bit more about this issue here: https://github.com/othiym23/node-continuation-local-storage/issues/6 - think most of this still applies, maybe @othiym23 can give an update if around.

**Comment by othiym23** [comment]
The Great CLS 4 Rewrite that I wanted to get to in 2015 didn't happen because I ran brutally short of time and attention for it, so yes, for the time being, shims like `cls-q` and `cls-bluebird` need to exist because of the way that their promise implementations break the continuation chain. Newer versions of `async-listener` take care of patching the microtask queue used by the core Promise implementation, and when I  (or somebody) does have time to do the next major version of CLS to automatically monkeypatch auxiliary libraries like Bluebird, CLS will do something similar without requiring users to know about shims. Since it seems like the issue has gotten sorted out here, I'm going to close this, but let me know if you have further questions that aren't answered in #6, and I'll see what I can do.
