### ISSUE TITLE
Losing Context with Async waterfall

### ISSUE THREAD

**Issue by coryt** [othiym23/node-continuation-local-storage#55]
The CLS context seems to be lost during async waterfall or series functions. It does appear to be working with parallel.

Tested with 
`node 5.0.0` and `node 5.3.0`
`cls 3.1.4`
`async 1.5.0`

Here is a simple test I've setup which fails on the 2nd waterfall function, the context _is_ available within the 1st waterfall function.  Am I doing something incorrect or is there an issue here?
```javascript
var async = require("async");
var should = require("should");
var cls = require("continuation-local-storage");

describe("API Context", function () {

    context("Test CLS",
        function () {

            it("it should provide context across async.waterfall flow",
                function (done) {
                    var ns = cls.createNamespace("test1");
                    var expectedDate = new Date();
                    ns.run(function () {
                        ns.set("currentDate", expectedDate);

                        async.waterfall(
                            [
                                function (next) {
                                    ns.get("currentDate").should.be.eql(expectedDate);
                                    next();
                                },
                                function (next) {
                                    ns.get("currentDate").should.be.eql(expectedDate);
                                    //cannot get access to context here
                                    next();
                                }
                            ],
                            function (err) {
                                ns.get("currentDate").should.be.eql(expectedDate);
                                //cannot get access to context here
                                done();
                            }
                        )

                    })
                }
            );
        });
});
```

**Comment by mpseidel** [comment]
+1 just stumbled upon this too - any hints on how to work arround this?

**Comment by mpseidel** [comment]
Update: false alarm in my case. 
My problem was not <code>waterfall</code> but calling <code>request</code> further down the line.

Fixed it by requiring <code>continuation-local-storage</code> before anything else.

See #44

**Comment by coryt** [comment]
Thanks @mpseidel this lead to solving my issue as well.
For the record, when requiring both async and cls, the order in which these are required matters so changing to the following resolves the issue. 
```
var cls = require("continuation-local-storage");
var async = require("async");
```

**Comment by amiram** [comment]
Thanks! this saved my life just now. I've used express-http-context and express-jwt together. The latter uses async.

**Comment by LiorRabin** [comment]
Hello, does the async.waterfall have to be inside ns.run for it to work?
