### ISSUE TITLE
.get returning undefined when inside an EventEmitter listener 

### ISSUE THREAD

**Issue by dazld** [othiym23/node-continuation-local-storage#6]
As per this gist:

https://gist.github.com/dazld/6493549

output is as follows:

```
in dispatch:  1337038180313
handler:  1337038180313
routeMatched listener:  undefined
```

seems like this should work, but can't see what might be causing the problem - any ideas..?

Using node 0.10.13 and CLS 2.1.1
- updated to 10.18 and output is the same.

**Comment by iliakan** [comment]
Just to put it clear.

Do I get it right that CLS won't work with mongodb (and hence mongoose) out of the box? 
Every query must be "fixed" to be CLS-aware?

**Comment by othiym23** [comment]
It will work some of the time, and with some effort (look at the MongoDB instrumentation in [`newrelic`](http://npm.im/newrelic) -- `lib/transaction/tracer/index.js` and `lib/instrumentation/mongodb.js` are the places to start) you can put together a shim that will take care of everything, but yeah, out of the box there are some holes. As I mention above, I would like to automate the shimming process, but there's a tricky trade-off between having CLS take care of these things automatically and keeping CLS as lightweight as possible. CLS isn't useful if it imposes a heavy overhead.

**Comment by othiym23** [comment]
Also, I'm pretty sure the original issue here is resolved, so I'm going to close this out. Requests and patches for better package-specific shims should be filed individually. Thanks!
