### ISSUE TITLE
Update async-listener to 0.6.0

### ISSUE THREAD

**Issue by matthewloring** [othiym23/node-continuation-local-storage#62]
Could the async-listener dependency be updated to get the new release?

**Comment by Qard** [comment]
@othiym23 Who has the appropriate super powers for this project? Looks like I have push/publish access to async-listener, but not CLS.

**Comment by matthewloring** [comment]
@Qard @othiym23 Ping on this. Who is the right person to talk to about getting a release out?

**Comment by matthewloring** [comment]
@othiym23 Would it be possible for @Qard to get publish access for CLS?

**Comment by othiym23** [comment]
It's done as of 1141774866cb09906ccb1429ccca047db0360334, and also, congratudolences, @Qard:

```
bauchelain% npm owner add qard continuation-local-storage
+ qard (continuation-local-storage)
```

Closing as resolved. Thanks for your patience, everybody! My day job is kind of absorbing.

**Comment by othiym23** [comment]
(also:

```
bauchelain% g pm && npm publish
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.35 KiB | 0 bytes/s, done.
Total 7 (delta 4), reused 0 (delta 0)
To git@github.com:othiym23/node-continuation-local-storage.git
   6b0b445..d5f3803  master -> master
 * [new tag]         v3.1.7 -> v3.1.7
+ continuation-local-storage@3.1.7
```)

**Comment by matthewloring** [comment]
@othiym23 Thanks!
