### ISSUE TITLE
missing context in express get/post/... callback

### ISSUE THREAD

**Issue by peaksnail** [othiym23/node-continuation-local-storage#73]
hi
I edit the express.application.handle like below
var namespace = cls.createNamespace('transaction');
express.application.handle = function(){
namespace.run(function cb(){
  namespace.bindEmitter(arguments[0]);
  namespace.bindEmitter(arguments[1]);
  namespace.set('uuid', require('node-uuid').v4());
  express.application.handle.apply(this, arguments);
});

and then I pring the uuid in express.get/post or some other http method, I found I can not get uuid
what's the prolem?

thanks!
zeng

**Comment by dazld** [comment]
With express 4, your handle function is never called. That doesn't look like a standard pattern..? 

The following works fine:

````
var express= require('express');
var app = express();
var cls = require('continuation-local-storage');
var assert = require('assert');

var namespace = cls.createNamespace('transaction');

// this is never called..? no logs
express.application.handle = function(){
    console.log('handler outer');
    namespace.run(function cb(){
        namespace.bindEmitter(arguments[0]);
        namespace.bindEmitter(arguments[1]);
        namespace.set('uuid', require('node-uuid').v4());
        console.log('handler cb');
        express.application.handle.apply(null, arguments);
    });
}

function handler(req, res) {

    var uuid = require('node-uuid').v4();

    namespace.run(function(){
        namespace.set('uuid', uuid);
        process.nextTick(function(){
            assert(uuid === namespace.get('uuid'));
            res.send(namespace.get('uuid'));
        });
    });
}

app.get('/', handler);
app.listen(3030);
```

Testing concurrency with apachebench as follows:
```
$ ab -c4 -n10000 http://localhost:3030/
```

...with no errors.

**Comment by peaksnail** [comment]
oh...
I debug in my express project,it realy console logs,my express version is 4.13.4

and I set express.application.handle = null; log like below 

[2016-07-11 17:42:53.895] [ERROR] console - TypeError: app.handle is not a function
    at Server.app (/angelia/projects/angelia-portal/angelia-portal/node_modules/express/lib/express.js:38

but I set express.application.handle = null in the examle you give ,it wors right

**Comment by dazld** [comment]
i couldn't find anything in the docs about how to use `express.application.handle` - where did you see this? 

anyway - this looks like an express problem, and not really a CLS thing.

**Comment by peaksnail** [comment]
express.application.handle is an innter function defined by express.application. And It's called in express.createServer.
It's really weird...

**Comment by dazld** [comment]
I guess you can close this, @peaksnail - btw, saw one more thing - using arguments from the `ns.run` function, instead of the arguments passed to `handle`. Almost certainly makes no difference here, but just noticed.
